https://www.youtube.com/watch?v=fIXh-gmR7mQ

## Slicing
### 1. 1d Array
### 2. 2d Array
### 3. 3d Array

<h2 style="color:blue" align="left"> 1d Array </h2>

![6_Slicing](image/Slicing_1.JPG)

![6_Slicing](image/Slicing_2.JPG)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
a[:]

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
a[:3]

array([1, 2, 3])

In [5]:
a[1:]

array([2, 3, 4, 5, 6, 7])

In [6]:
a[2:5]

array([3, 4, 5])

In [7]:
a[1:4]

array([2, 3, 4])

In [8]:
a[1::2]

array([2, 4, 6])

In [9]:
a[-1:]

array([7])

In [10]:
a[-5:]

array([3, 4, 5, 6, 7])

In [11]:
a[-5:-2]

array([3, 4, 5])

In [12]:
a[-5:0]

array([], dtype=int32)

![6_Slicing](image/Slicing_3.JPG)

-------------------------------------------------------------------------------------------------------------------------------

<h2 style="color:blue" align="left"> 2d Array </h2>

![6_Slicing](image/Slicing_4.JPG)

In [13]:
x = np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
x[1:,1:]

array([[4],
       [6]])

In [15]:
x[::]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
b = np.array([[1,2,3,4],[5,6,7,8],[20,20,40,50]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [20, 20, 40, 50]])

In [17]:
b[1:,1:]

array([[ 6,  7,  8],
       [20, 40, 50]])

![6_Slicing](image/Slicing_5.JPG)

In [18]:
b[::,::2]                  # Entire rows & Entire columns with step of 2
                           # start:end:step ---> ::  ---> Not mentioned start / end / step ---> Entire row / column

array([[ 1,  3],
       [ 5,  7],
       [20, 40]])

-------------------------------------------------------------------------------------------------------------------------------

<h2 style="color:blue" align="left"> 3d Array </h2>

![6_Slicing](image/Slicing_6.JPG)

![6_Slicing](image/Slicing_7.JPG)

In [19]:
c = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]
d = np.array(c)
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [20]:
d[:,:,:1]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

![6_Slicing](image/Slicing_8.JPG)

In [21]:
d[:,1:,::2]

array([[[ 5,  7],
        [ 9, 11]],

       [[17, 19],
        [21, 23]]])