In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("F:/03. Suresh/1. Material/05. Data Science/01. Simlilearn/data set/iris_dataset.csv")
df.head(10)

sepal length  sepal width  petal length  petal width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

-------------------------------------------------------------------------------------------------------------------------------

## DataFrame Details

        
        1. Index
        
        2. Columns
        
        3. Values
        
        4. Shape
        
        5. Size
        
        6. Statistics

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> 1. Index <h3>

In [4]:
print (df.index)

RangeIndex(start=0, stop=150, step=1)


-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> 2. Columns <h3>

In [6]:
print (df.columns)

Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'iris'], dtype='object')


-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> 3. Values <h3>

In [11]:
df.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [16]:
df["petal width"].values

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [13]:
df["petal width"].values[0]

0.2

In [15]:
df["petal width"].values[67]

1.0

In [17]:
df["petal width"].values[0:10]

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1])

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> 4. Shape <h3>

In [4]:
df.shape

(150, 5)

In [5]:
df.ndim

2

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> 5. Size <h3>

In [18]:
df.count()

sepal length    147
sepal width     147
petal length    147
petal width     147
iris            147
dtype: int64

In [20]:
df.size

735

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> 6. Statistics <h3>

In [23]:
df.describe()

sepal length  sepal width  petal length  petal width
count    147.000000   147.000000    147.000000   147.000000
mean       5.856463     3.055782      3.780272     1.208844
std        0.829100     0.437009      1.759111     0.757874
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> Cumulative Sum <h3>

In [25]:
y = pd.DataFrame({'one': pd.Series(range(5)),
                 'two': pd.Series(range(5, 10)),
                 'three': pd.Series(list('abcde'))})

print ('head =>\n', y.head()), '\n'
print ('cumsum =>\n', y.cumsum()), '\n'

head =>
    one  two three
0    0    5     a
1    1    6     b
2    2    7     c
3    3    8     d
4    4    9     e
cumsum =>
   one two  three
0   0   5      a
1   1  11     ab
2   3  18    abc
3   6  26   abcd
4  10  35  abcde


(None, '\n')

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> Cumulative Product <h3>

In [27]:
print ('cumprod =>\n', y[['one', 'two']].cumprod()), '\n'

cumprod =>
    one    two
0    0      5
1    0     30
2    0    210
3    0   1680
4    0  15120


(None, '\n')

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> Cumulative Maximum <h3>

In [30]:
print ('rev =>\n', y.iloc[::-1]), '\n',
print ('cummax =>\n', y.iloc[::-1].cummax()), '\n'

rev =>
    one  two three
4    4    9     e
3    3    8     d
2    2    7     c
1    1    6     b
0    0    5     a
cummax =>
   one two three
4   4   9     e
3   4   9     e
2   4   9     e
1   4   9     e
0   4   9     e


(None, '\n')

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> Cumulative Minimum <h3>

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> Index of Min and Max Values <h3>

In [38]:
import random

In [44]:
y = pd.DataFrame({'one': pd.Series(random.sample(range(100), 5), index=list('abcde')),
                 'two': pd.Series(random.sample(range(100), 5), index=list('abcde')),
                 'three': pd.Series(list('ABCDE'), index=list('abcde'))})
print (y), '\n'
print ('idxmax =>\n', y[['one', 'two']].idxmax()), '\n'
print ('idxmin =>\n', y[['one', 'two']].idxmin()), '\n'

   one  two three
a   70   19     A
b   69   71     B
c   10   14     C
d   47   65     D
e   74   23     E
idxmax =>
 one    e
two    b
dtype: object
idxmin =>
 one    c
two    c
dtype: object


(None, '\n')

-------------------------------------------------------------------------------------------------------------------------------

<h3 style="color:blue" align="left"> Value_Counts <h3>

In [48]:
print ('top 10 =>\n', df.head(10)), '\n'
print ('value_counts =>\n', df['petal length'].value_counts().head(10))

top 10 =>
    sepal length  sepal width  petal length  petal width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa
value_counts =>
 1.5    12
1.4    12
4.5     8
5.1     7
1.3     7
1.6     7
5.6     6
4.0     5
4.9     5
4.7     5
Name: petal length, dtype: int64


-------------------------------------------------------------------------------------------------------------------------------

In [8]:
df[57:60]

sepal length  sepal width  petal length  petal width             iris
57           4.9          2.4           3.3          1.0  Iris-versicolor
58           6.6          2.9           4.6          1.3  Iris-versicolor
59           5.2          2.7           3.9          1.4  Iris-versicolor

In [9]:
df.loc[149]

sepal length               5.9
sepal width                  3
petal length               5.1
petal width                1.8
iris            Iris-virginica
Name: 149, dtype: object

In [11]:
df.iloc[149]

sepal length               5.9
sepal width                  3
petal length               5.1
petal width                1.8
iris            Iris-virginica
Name: 149, dtype: object

In [10]:
df.ix[149]

C:\Users\deepusuresh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


sepal length               5.9
sepal width                  3
petal length               5.1
petal width                1.8
iris            Iris-virginica
Name: 149, dtype: object

In [12]:
df.iris[5:7]

5    Iris-setosa
6    Iris-setosa
Name: iris, dtype: object

In [18]:
# Create the column Child and assign to 0
df["Child"] = 0

In [8]:
df.head(10)

sepal length  sepal width  petal length  petal width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [7]:
df = df.drop_duplicates()
df.head(15)

sepal length  sepal width  petal length  petal width         iris
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa